### ISSUE TITLE
CGEventGetEventRecord has been renamed

### ISSUE THREAD

**Issue by avaidyam** [NUIKit/GraphicsServices#1]
You'll want to use `SLEventGetEventRecord` instead on macOS 10.12+.

**Comment by avaidyam** [comment]
Also, random aside, but `GSApp.c` is missing an `#include <mach/mach_port.h>`.

**Comment by avaidyam** [comment]
Also, decompiling and messing with `HIToolbox` tells me that, ironically, `HIToolbox` does the exact same thing as `GraphicsServices` here attempts to do... but it's fun to reimplement things!

**Comment by CodaFi** [comment]
I should hope it looks the same on the inside, it’s kinda the point!  The API, however, is ripped from the purple event system in iOS.

**Comment by avaidyam** [comment]
Food for thought: If Purple and HIToolbox are doing the exact same things, is HIToolbox really so bad? 🤔

**Comment by CodaFi** [comment]
Go look into the architecture of Purple eventing versus HIToolbox eventing and get back to me about whether they're doing "the exact same thing" 🙃

**Comment by CodaFi** [comment]
Resolved by 1c8415217c7550e71b993f9eedde5a20ff2b1ce0

I suspect we don't need the event record if HIToolbox has found a way around it.
